
#define FIRMWARE_VERSION_MAJOR 2
#define FIRMWARE_VERSION_MINOR 6
#define FIRMWARE_VERSION_PATCH 0
#define FIRMWARE_VERSION_BUILD 0


// clang-format off

#ifndef EXTENDED_VERSION
#define EXTENDED_VERSION \
    STRINGIZE(FIRMWARE_VERSION_MAJOR) "." \
    STRINGIZE(FIRMWARE_VERSION_MINOR) "." \
    STRINGIZE(FIRMWARE_VERSION_PATCH) "+" \
    __DATE__ "-" \
    __TIME__
#endif
