
set(ASF_DIR ${CMAKE_CURRENT_SOURCE_DIR} PARENT_SCOPE)

add_library(ASF_lib STATIC 
        "./common/utils/stdio/read.c"
        "./common/utils/stdio/write.c" 
        "./common/services/sleepmgr/sam/sleepmgr.c"
        "./common/services/usb/class/cdc/device/udi_cdc.c"
        "./common/services/usb/udc/udc.c"
        "./common/services/usb/class/cdc/device/udi_cdc_desc.c"
        "./common/services/clock/sams70/sysclk.c"
        "./sam/drivers/usart/usart.c"
        "./sam/drivers/pio/pio_handler.c"
        "./sam/drivers/tc/tc.c"
        "./sam/drivers/usbhs/usbhs_device.c"
        "./sam/drivers/xdmac/xdmac.c"
        "./sam/drivers/pio/pio.c"
        "./sam/drivers/spi/spi.c"
        "./sam/drivers/qspi/qspi.c"
        "./sam/drivers/pmc/pmc.c"
        "./sam/drivers/twihs/twihs.c"
        "./sam/drivers/uart/uart.c"
        "./sam/drivers/pmc/sleep.c"
        "./sam/drivers/rstc/rstc.c"
        "./sam/drivers/efc/efc.c"
        "./common/boards/user_board/init.c"
        "./common/utils/interrupt/interrupt_sam_nvic.c"
        "./sam/utils/cmsis/sams70/source/templates/gcc/startup_sams70.c"
        "./sam/utils/cmsis/sams70/source/templates/system_sams70.c"
    )

target_include_directories( ASF_lib 
    PUBLIC
        "../../../../sources"
        "../../config"
        "./common/boards"
        "./common/utils"
        "./common/boards/user_board"
        "./common/services/clock"
        "./common/services/ioport"
        "./common/services/sleepmgr"
        "./common/services/usb"
        "./common/services/usb/class/cdc"
        "./common/services/usb/class/cdc/device"
        "./common/services/usb/udc"
        "./common/services/serial/sam_uart"
        "./common/services/serial"
        "./common/utils/stdio/stdio_serial"
        "./sam/utils"
        "./sam/utils/header_files"
        "./sam/utils/preprocessor"
        "./sam/utils/fpu"
        "./sam/utils/cmsis/sams70/source/templates"
        "./sam/utils/cmsis/sams70/include"
        "./sam/drivers/pmc"
        "./sam/drivers/twihs"
        "./sam/drivers/uart"
        "./sam/drivers/qspi"
        "./sam/drivers/pio"
        "./sam/drivers/usbhs"
        "./sam/drivers/xdmac"
        "./sam/drivers/tc"
        "./sam/drivers/usart"
        "./sam/drivers/spi" 
        "./sam/drivers/efc" 
        "./sam/drivers/matrix" 
        "./sam/drivers/rstc/example1" 
        "./sam/drivers/rstc"
        "./thirdparty/CMSIS/Include"
        "./thirdparty/CMSIS/Lib/GCC"
)




